import { App, Editor, FileSystemAdapter, MarkdownView, Modal, Notice, Plugin, PluginSettingTab, Setting, TFile } from "obsidian";
import * as path from "path";
import { applyPlan, planSync, PlannedWrite, SyncQueue, TARGETS, validateProjectRoot } from "./sync";

interface AIContextSyncSettings {
  version: number;
  sourceNotePath: string;
  autoSyncOnSave: boolean;
  showStatusBar: boolean;
  syncTargets: { id: string; enabled: boolean }[];
  customHeader: string;
  includeTimestamp: boolean;
  projectPaths: string[];
}

export function normalizeSettings(saved: Partial<AIContextSyncSettings> = {}): AIContextSyncSettings {
  const oldTargets = Array.isArray(saved.syncTargets) ? saved.syncTargets : [];
  return {
    version: 2,
    sourceNotePath: typeof saved.sourceNotePath === "string" ? saved.sourceNotePath : "",
    // Upgrading from whole-file writes requires a fresh opt-in to auto-sync.
    autoSyncOnSave: saved.version === 2 && saved.autoSyncOnSave === true,
    showStatusBar: saved.showStatusBar !== false,
    syncTargets: TARGETS.map(target => ({
      id: target.id,
      enabled: oldTargets.some(item => item && (item.id === target.id || (target.id === "agents" && item.id === "codex")) && item.enabled === true),
    })),
    customHeader: typeof saved.customHeader === "string" ? saved.customHeader : "<!-- Context generated by AI Context Sync. Edit the Obsidian source note. -->",
    includeTimestamp: saved.includeTimestamp === true,
    projectPaths: Array.isArray(saved.projectPaths) ? saved.projectPaths.filter((item): item is string => typeof item === "string") : [],
  };
}

export default class AIContextSyncPlugin extends Plugin {
  settings = normalizeSettings();
  statusBarItem: HTMLElement | null = null;
  private queue = new SyncQueue();
  private autoTimer: ReturnType<typeof setTimeout> | undefined;
  private revision = 0;
  private unloaded = false;

  async onload() {
    const saved = await this.loadData();
    this.settings = normalizeSettings(saved ?? {});
    this.unloaded = false;
    this.refreshStatusBar();
    this.addCommand({ id: "sync-ai-context", name: "Sync AI context to enabled targets", callback: () => this.syncToAllTargets() });
    this.addCommand({ id: "preview-ai-context", name: "Preview sync destinations", callback: () => this.previewSync() });
    this.addCommand({ id: "sync-ai-context-select", name: "Sync AI context to one enabled target", callback: () => new TargetSelectorModal(this.app, this).open() });
    this.addCommand({
      id: "set-source-note", name: "Set current note as AI context source",
      editorCallback: async (_editor: Editor, view: MarkdownView) => {
        if (!view.file) return;
        this.settings.sourceNotePath = view.file.path;
        await this.saveSettings();
        new Notice(`AI Context source: ${view.file.path}`);
      },
    });
    this.addCommand({ id: "add-project-path", name: "Add existing project directory", callback: () => this.showAddProjectPathModal() });
    this.addCommand({ id: "create-ai-context-template", name: "Create AI context template note", callback: () => this.createTemplateNote() });
    // Always register once. The listener checks the current toggle, not its value at load.
    this.registerEvent(this.app.vault.on("modify", file => {
      if (!this.unloaded && this.settings.autoSyncOnSave && file instanceof TFile && file.path === this.settings.sourceNotePath) {
        this.cancelPendingAutoSync();
        const scheduledRevision = this.revision;
        this.autoTimer = setTimeout(() => {
          this.autoTimer = undefined;
          void this.sync(undefined, true, scheduledRevision);
        }, 500);
      }
    }));
    this.addSettingTab(new AIContextSyncSettingTab(this.app, this));
    this.addRibbonIcon("refresh-cw", "Sync AI context", () => { void this.syncToAllTargets(); });
    if (saved && saved.version !== 2) {
      new Notice("AI Context Sync now preserves managed sections. Auto-sync is off after upgrade. Review targets and preview a manual sync before enabling it.", 12000);
    }
  }

  onunload() {
    this.unloaded = true;
    this.cancelPendingAutoSync();
  }

  private cancelPendingAutoSync() {
    if (this.autoTimer !== undefined) clearTimeout(this.autoTimer);
    this.autoTimer = undefined;
  }

  async saveSettings() {
    this.revision++;
    this.cancelPendingAutoSync();
    await this.saveData(this.settings);
  }

  refreshStatusBar() {
    this.statusBarItem?.remove();
    this.statusBarItem = this.settings.showStatusBar ? this.addStatusBarItem() : null;
    this.updateStatusBar("Ready");
  }

  private updateStatusBar(status: string) {
    this.statusBarItem?.setText(`AI Sync: ${status}`);
  }

  private async createPlan(targetId?: string, automatic = false): Promise<PlannedWrite[] | null> {
    if (this.unloaded || (automatic && !this.settings.autoSyncOnSave)) return null;
    const revision = this.revision;
    const snapshot = JSON.parse(JSON.stringify(this.settings)) as AIContextSyncSettings;
    const source = this.app.vault.getAbstractFileByPath(snapshot.sourceNotePath);
    if (!(source instanceof TFile)) throw new Error("Select an existing source note first.");
    const targets = snapshot.syncTargets.filter(target => target.enabled && (!targetId || target.id === targetId)).map(target => target.id);
    const adapter = this.app.vault.adapter;
    if (!(adapter instanceof FileSystemAdapter)) throw new Error("AI Context Sync requires a desktop vault on the local filesystem.");
    const content = await this.app.vault.read(source);
    if (this.unloaded || (automatic && !this.settings.autoSyncOnSave)) return null;
    if (revision !== this.revision) throw new Error("Sync settings changed while reading the note. Review settings and sync again.");
    const header = snapshot.customHeader + (snapshot.includeTimestamp ? "\n<!-- Last synced: {{TIMESTAMP}} -->" : "");
    return planSync(snapshot.projectPaths, targets, content, {
      source: source.path,
      sourceAbsolutePath: path.join(adapter.getBasePath(), source.path),
      header,
      timestamp: new Date().toISOString(),
    });
  }

  private sync(targetId?: string, automatic = false, scheduledRevision?: number): Promise<void> {
    return this.queue.enqueue(async () => {
      try {
        if (automatic && scheduledRevision !== undefined && scheduledRevision !== this.revision) return;
        const plan = await this.createPlan(targetId, automatic);
        if (!plan) return;
        this.updateStatusBar("Syncing");
        const count = applyPlan(plan);
        this.updateStatusBar("Synced");
        new Notice(`AI Context Sync: ${count} file(s) updated; ${plan.length - count} unchanged.`);
      } catch (error) {
        if (this.unloaded) return;
        this.updateStatusBar("Error");
        new Notice(`AI Context Sync: ${(error as Error).message}`, 10000);
      }
    });
  }

  syncToAllTargets() { return this.sync(); }
  syncToSpecificTarget(targetId: string) { return this.sync(targetId); }

  previewSync(): Promise<void> {
    return this.queue.enqueue(async () => {
      try {
        const plan = await this.createPlan();
        if (plan) new PreviewModal(this.app, plan).open();
      } catch (error) { new Notice(`AI Context Sync: ${(error as Error).message}`, 10000); }
    });
  }

  async setAutoSync(enabled: boolean): Promise<void> {
    if (enabled) {
      try {
        const plan = await this.queue.enqueue(() => this.createPlan());
        if (!plan) return;
      } catch (error) {
        new Notice(`Auto-sync remains off: ${(error as Error).message}`, 10000);
        return;
      }
    }
    this.settings.autoSyncOnSave = enabled;
    await this.saveSettings();
    new Notice(enabled ? "Auto-sync enabled for future source edits." : "Auto-sync disabled; pending automatic syncs cancelled.");
  }

  showAddProjectPathModal() { new AddProjectPathModal(this.app, this).open(); }

  async createTemplateNote() {
    const fileName = "AI Context.md";
    const existing = this.app.vault.getAbstractFileByPath(fileName);
    if (existing) {
      if (existing instanceof TFile) await this.app.workspace.getLeaf().openFile(existing);
      new Notice("AI Context.md already exists; it was not changed.");
      return;
    }
    const source = await this.app.vault.create(fileName, "---\ntype: note\ntags: [ai-context]\n---\n\n# Project context\n\nDescribe the project, conventions, and decisions assistants should know.\n");
    this.settings.sourceNotePath = source.path;
    await this.saveSettings();
    await this.app.workspace.getLeaf().openFile(source);
  }
}

class PreviewModal extends Modal {
  constructor(app: App, private plan: PlannedWrite[]) { super(app); }
  onOpen() {
    this.contentEl.createEl("h2", { text: "Sync destinations" });
    this.contentEl.createEl("p", { text: "Sync updates only the marked AI Context Sync section. Existing text outside that section is preserved. Each sync revalidates these files." });
    const list = this.contentEl.createEl("ul");
    for (const item of this.plan) list.createEl("li", { text: `${item.previous === null ? "Create" : item.previous === item.next ? "Unchanged" : "Update section"}: ${item.destination}` });
    this.contentEl.createEl("p", { text: "Close this preview, then run Sync AI context when ready. No files were written by this preview." });
  }
  onClose() { this.contentEl.empty(); }
}

class TargetSelectorModal extends Modal {
  constructor(app: App, private plugin: AIContextSyncPlugin) { super(app); }
  onOpen() {
    this.contentEl.createEl("h2", { text: "Select enabled target" });
    for (const target of TARGETS.filter(target => this.plugin.settings.syncTargets.some(saved => saved.id === target.id && saved.enabled))) {
      new Setting(this.contentEl).setName(target.name).setDesc(target.outputPath).addButton(button => button.setButtonText("Sync").onClick(() => { void this.plugin.syncToSpecificTarget(target.id); this.close(); }));
    }
  }
  onClose() { this.contentEl.empty(); }
}

class AddProjectPathModal extends Modal {
  constructor(app: App, private plugin: AIContextSyncPlugin) { super(app); }
  onOpen() {
    this.contentEl.createEl("h2", { text: "Add existing project directory" });
    this.contentEl.createEl("p", { text: "Use an absolute path to an existing local project. No directory is created for a missing or mistyped project path." });
    let value = "";
    new Setting(this.contentEl).setName("Project directory").addText(text => text.setPlaceholder("/absolute/path/to/project").onChange(next => { value = next; }));
    new Setting(this.contentEl).addButton(button => button.setButtonText("Add").setCta().onClick(async () => {
      try {
        const root = validateProjectRoot(value.trim());
        if (this.plugin.settings.projectPaths.some(project => validateProjectRoot(project) === root)) throw new Error("That project directory is already configured.");
        this.plugin.settings.projectPaths.push(root);
        await this.plugin.saveSettings();
        new Notice(`Added project: ${root}`);
        this.close();
      } catch (error) { new Notice((error as Error).message, 10000); }
    }));
  }
  onClose() { this.contentEl.empty(); }
}

class AIContextSyncSettingTab extends PluginSettingTab {
  constructor(app: App, private plugin: AIContextSyncPlugin) { super(app, plugin); }
  display() {
    const el = this.containerEl;
    el.empty();
    el.createEl("h2", { text: "AI Context Sync" });
    el.createEl("p", { text: "Choose a source note, explicit project directories, and targets. Preview and sync manually before opting into auto-sync. Disabling a target does not delete its generated section." });
    new Setting(el).setName("Source note").setDesc("Path within this vault; you can also use Set current note as AI context source.").addText(text => text.setValue(this.plugin.settings.sourceNotePath).onChange(async value => { this.plugin.settings.sourceNotePath = value; await this.plugin.saveSettings(); }));
    new Setting(el).setName("Auto-sync on save").setDesc("Off by default. Applies immediately; disabling cancels pending automatic writes.").addToggle(toggle => toggle.setValue(this.plugin.settings.autoSyncOnSave).onChange(async value => { await this.plugin.setAutoSync(value); this.display(); }));
    new Setting(el).setName("Show status bar").addToggle(toggle => toggle.setValue(this.plugin.settings.showStatusBar).onChange(async value => { this.plugin.settings.showStatusBar = value; await this.plugin.saveSettings(); this.plugin.refreshStatusBar(); }));
    el.createEl("h3", { text: "Targets" });
    for (const target of TARGETS) {
      const saved = this.plugin.settings.syncTargets.find(item => item.id === target.id)!;
      new Setting(el).setName(target.name).setDesc(target.outputPath).addToggle(toggle => toggle.setValue(saved.enabled).onChange(async value => { saved.enabled = value; await this.plugin.saveSettings(); }));
    }
    el.createEl("h3", { text: "Project directories" });
    if (!this.plugin.settings.projectPaths.length) el.createEl("p", { text: "No project directories configured. The vault root is never used automatically." });
    for (const project of this.plugin.settings.projectPaths) {
      new Setting(el).setName(project).addButton(button => button.setButtonText("Remove").onClick(async () => {
        this.plugin.settings.projectPaths = this.plugin.settings.projectPaths.filter(item => item !== project);
        await this.plugin.saveSettings(); this.display();
      }));
    }
    new Setting(el).addButton(button => button.setButtonText("Add project directory").onClick(() => this.plugin.showAddProjectPathModal()));
    el.createEl("h3", { text: "Generated section" });
    new Setting(el).setName("Header").setDesc("Optional text. {{SOURCE}} and {{TIMESTAMP}} are replaced literally; source content is never processed as a template.").addTextArea(text => text.setValue(this.plugin.settings.customHeader).onChange(async value => { this.plugin.settings.customHeader = value; await this.plugin.saveSettings(); }));
    new Setting(el).setName("Include sync timestamp").setDesc("Off by default to avoid changes when content is unchanged.").addToggle(toggle => toggle.setValue(this.plugin.settings.includeTimestamp).onChange(async value => { this.plugin.settings.includeTimestamp = value; await this.plugin.saveSettings(); }));
    new Setting(el).setName("Review and sync").addButton(button => button.setButtonText("Preview").onClick(() => { void this.plugin.previewSync(); })).addButton(button => button.setButtonText("Sync now").onClick(() => { void this.plugin.syncToAllTargets(); }));
  }
}
